#!/usr/local/bin/python2.7

'''
The prime factors of 13195 are 5, 7, 13 and 29.
What is the largest prime factor of the number 600851475143?
'''

import sys
import itertools


def isPrime(number):
	# borrowed this function from 
	# https://www.daniweb.com/software-development/python/code/216880/check-if-a-number-is-a-prime-number-python
    '''check if integer n is a prime'''
    # make sure n is a positive integer
    number = abs(int(number))
    # 0 and 1 are not primes
    if number < 2:
        return False
    # 2 is the only even prime number
    if number == 2: 
        return True    
    # all other even numbers are not primes
    if not number & 1: 
        return False
    # range starts with 3 and only needs to go up the squareroot of n
    # for all odd numbers
    for x in range(3, int(number**0.5)+1, 2):
        if number % x == 0:
            return False
    return True

def isPrimeFactor(x):	
	if 600851475143 % x== 0:
		return True
	else:
		return False
		

for x in itertools.count(600851475143, -1):
	if isPrime(x):
		#print x
		if isPrimeFactor(x):
			print str(x) + " is the largest prime factor of the number."
			sys.exit()
	


